services:
  # Servicio para PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users_bd
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Servicio para la API de Node.js
  api:
    build: .
    container_name: api
    ports:
    - "4000:4000" 
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: users_bd
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network

  # Servicio para Liquibase
  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    environment:
      LIQUIBASE_URL: jdbc:postgresql://db:5432/users_bd
      LIQUIBASE_USER: postgres
      LIQUIBASE_PASSWORD: 1234
    volumes:
      - ./db.changelog-master.xml:/liquibase/changelog/db.changelog-master.xml
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
